WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f44042fa840>: Failed to resolve 'none' ([Errno -3] Temporary failure in name resolution)")': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4403cc9340>: Failed to resolve 'none' ([Errno -3] Temporary failure in name resolution)")': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4403cc9fd0>: Failed to resolve 'none' ([Errno -3] Temporary failure in name resolution)")': /wd/hub/session